'''
Reads files, makes plots
'''
import os.path
import matplotlib.pyplot as plt
import numpy as np


def read_data():
    '''
    Reads data generated by the solver, returns data as seperate arrays


    Args:


    Returns:


    '''
    path = input('Pls give Ordner: ')

    energies_path = os.path.join(path, 'energies.dat')
    potential_path = os.path.join(path, 'potential.dat')
    wavefuncs_path = os.path.join(path, 'wavefuncs.dat')
    expvalues_path = os.path.join(path, 'expvalues.dat')

    energies = np.loadtxt(energies_path)
    potential = np.loadtxt(potential_path)
    wavefuncs = np.loadtxt(wavefuncs_path)
    expvalues = np.loadtxt(expvalues_path)

    return energies, potential, wavefuncs, expvalues

def ploty():
    '''
    gggg
    '''
    energies, potential, wavefuncs, expvalues = read_data()

    plt.subplot(1,2,1)
    plt.plot(potential[:, 0],potential[:,1])
    plt.title(r'Potential, eigenstates, $\langle \mathrm{x} \rangle$')
    #plt.hlines()
    plt.xlabel('x [Bohr]' )
    plt.ylabel('Energy [Hartree]')

    plt.subplot(1,2,2)
    plt.title(r'$ \sigma_x $')
    plt.xlabel('x [Bohr]')
    plt.plot(potential,potential)
    plt.show()
ploty()
