import os.path
import matplotlib.pyplot as plt
import numpy as np


def read_data(path):
    '''
    Reads data generated by the solver, returns data as seperate arrays


    Args:


    Returns:


    '''

    energies_path = os.path.join(path, 'energies.dat')
    potential_path = os.path.join(path, 'potential.dat')
    wavefuncs_path = os.path.join(path, 'wavefuncs.dat') 
    expvalues_path = os.path.join(path, 'expvalues.dat')

    energies = np.loadtxt(energies_path)
    potential = np.loadtxt(potential_path)
    wavefuncs = np.loadtxt(wavefuncs_path)
    expvalues = np.loadtxt(expvalues_path)

    return
    



def ploty():
    '''

    '''

