import os.path
import matplotlib.pyplot as plt
import numpy as np


def read_data(path):
    '''
    Reads data generated by the solver, returns data as seperate arrays


    Args:


    Returns:


    '''

    energies_path = os.path.join(path, 'energies.dat')
    potential_path = os.path.join(path, 'potential.dat')
    wavefuncs_path = os.path.join(path, 'wavefuncs.dat') 
    expvalues_path = os.path.join(path, 'expvalues.dat')

    energies = np.loadtxt(energies_path)
    potential = np.loadtxt(potential_path)
    wavefuncs = np.loadtxt(wavefuncs_path)
    expvalues = np.loadtxt(expvalues_path)

    return energies, potential, wavefuncs, expvalues
    



def ploty():
    '''

    '''
    x = [1,2,3,4,5]
    potential = [0,4,5,6,7]
    plt.plot(x, potential)
    plt.title(r'Potential, eigenstates, $\langle \mathrm{x} \rangle$')
    plt.xlabel('x [Bohr]' )
    plt.ylabel('Energy [Hartree]')   
    plt.show()
ploty()
